### ISSUE TITLE
lizardfs-tm_mad driver integration

### ISSUE THREAD

**Issue by mosharaflink** [cloudweavers/lizardfs-tm_mad#1]
Hi,
I have put lizardfs-tm_mad driver under "/var/lib/one/remotes/tm/lizardfs/" and config the /etc/one/oned.conf and change the conf like follwoing

TM_MAD = [
    EXECUTABLE = "one_tm",
    ARGUMENTS = "-t 15 -d dummy,lvm,shared,fs_lvm,qcow2,ssh,ceph,dev,vcenter,iscsi_libvirt,lizardfs"
]

service opennebula restart
service opennebula-sunstone restart
As oneadmin user sync the remote scripts:
su - oneadmin -c 'onehost sync --force'

After restarting the services I am agetting error of "Error monitoring datastore 0: System datastore driver 'lizardfs' not available". Is there any others configuration to do for lizardfs?

**Comment by cloudweavers** [comment]
You have to install the dm_mad drivers as well:
https://github.com/cloudweavers/lizardfs-DM_MAD

if you want to add Datastore support: Create a lizardfs directory in the datastore directory, and add the files in the repo https://github.com/cloudweavers/lizardfs-DM_MAD In the one.conf file add "lizardfs" in the section

**Comment by mosharaflink** [comment]
Hi,

Thank you for reply and update status.


I also have added lizardfs in TM_MAD and DATASTORE_MAD section. Also we
need to add in "TM_MAD_CONF" section. So for "TM_MAD_CONF" section what
will be the configuration??



Thanks
Mosharaf

**Comment by ioiioi** [comment]
I think might be I got the tm_mad_conf and tm_mad_conf to work with lizardfs driver, here it is:
```
TM_MAD_CONF = [
    NAME = "lizardfs",
    LN_TARGET = "NONE",
    CLONE_TARGET = "SYSTEM",
    SHARED = "YES",
    DS_MIGRATE = "YES",
    ALLOW_ORPHANS = "NO"
]
```

```
DS_MAD_CONF = [
    NAME = "lizardfs",
    REQUIRED_ATTRS = "",
    PERSISTENT_ONLY = "NO",
    MARKETPLACE_ACTIONS = "export"
]
```

**Comment by cloudweavers** [comment]
many thanks for your contribution. May I add them to the README.md with attribution to you?

**Comment by baby-gnu** [comment]
They are now included, so could be closed.

Regards.
