### ISSUE TITLE
LizardFS TM_MAD does not work with OpenNebula 5.8

### ISSUE THREAD

**Issue by mclei** [cloudweavers/lizardfs-tm_mad#2]
After upgrading to OpenNebula 5.8 I am getting error:
"Image Datastore does not support transfer mode: shared"
when trying to deploy VM.

**Comment by mclei** [comment]
Found the problem with added attributes for shared datastore in TM_MAD.
My complete TM_MAD config for LizardFS is now:
```
TM_MAD_CONF = [
    NAME = "lizardfs",
    LN_TARGET = "NONE",
    CLONE_TARGET = "SYSTEM",
    SHARED = "YES",
    DS_MIGRATE = "YES",
    ALLOW_ORPHANS = "NO",

    TM_MAD_SYSTEM = "shared",
    LN_TARGET_SHARED = "NONE",
    CLONE_TARGET_SHARED = "SYSTEM",
    DISK_TYPE_SHARED = "FILE"
]
```

Hope it is ok and helps somebody.
After oned restart, each datastore using this TM_MAD must be updated. It gets updated for example when added and removed DESCRIPTION attribute to datastore.

Leaving opened to be added to documentation.

**Comment by baby-gnu** [comment]
It's now integrated in `README.md` so can be closed.

Regards.
