### ISSUE TITLE
Disk snapshots are using cp

### ISSUE THREAD

**Issue by mclei-asw** [cloudweavers/lizardfs-tm_mad#3]
I have found that disk snapshots are using "cp" command (tm/lizardfs/snap_create).
Is there any reason to not use lizardfs makesnapshot, the same as clone uses?

**Comment by cloudweavers** [comment]
You are right! We simply don't use the OpenNebula snapshots (we have implemented an alternative approach) and so we simply didn't change that remote script. I will update it.

**Comment by mclei-asw** [comment]
Maybe the similar problem with resize, where appendchunks could be effectively used.

**Comment by mclei** [comment]
There is a bug in current save_as implementation. When save_as is applied to persistent disk of VM, then only symlink is copied and not disk data! Will make a pull request soon.

**Comment by mclei-asw** [comment]
Created pull request #5.

**Comment by baby-gnu** [comment]
The pull request in merged, I think this issue can be closed.

Regards.
